name: test_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.0.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  hive_flutter: ^1.1.0
  talker_bloc_logger: ^4.7.6
  talker_flutter: ^4.7.6
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2

dependency_overrides:
  source_gen: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
